# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"

kreta_task_manager_remove_member_from_organization:
    path: /organization/{organizationId}/member/{userId}
    defaults:
        _controller: "kreta.task_manager.http_action.remove_member_from_organization:__invoke"
    methods:
        - DELETE

